#!/usr/bin/env python3
"""
Finds parameters that are defined in UDB but that nothing in the ISA model
reads.

The criterion for this project is that a parameter describes observable
architectural state that can differ between implementations. A parameter that
no CSR field, instruction or IDL function consults cannot, as modelled, change
any observable state: setting it to one value or another produces an identical
machine. That makes it a useful mechanical proxy for the failure mode the
project is trying to avoid.

Two tiers are reported, because they are not the same problem:

  set_but_unread  a config under cfgs/ assigns the parameter a value, but no
                  file under spec/std/isa/ references it. This is the sharper
                  case: it looks wired up and is not.
  unreferenced    the name does not appear anywhere outside its own definition.

Neither is automatically a defect. A parameter may be defined ahead of the IDL
that will consume it, which appears to be the case for much of the vector set.
The point is that the distinction is mechanical and currently invisible.

Usage:
    python scripts/orphan_params.py --udb-root /path/to/riscv-unified-db
"""

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MODEL_DIRS = ["spec/std/isa/csr", "spec/std/isa/inst", "spec/std/isa/isa",
              "spec/std/isa/ext", "spec/std/isa/profile", "spec/std/isa/proc_cert"]
SUFFIXES = {".yaml", ".yml", ".idl", ".isa"}


def read_tree(root: Path, subdirs):
    out = {}
    for sub in subdirs:
        d = root / sub
        if not d.is_dir():
            continue
        for p in d.rglob("*"):
            if p.is_file() and p.suffix in SUFFIXES:
                try:
                    out[p] = p.read_text(errors="ignore")
                except Exception:
                    pass
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--udb-root", required=True, type=Path)
    ap.add_argument("--revision", default="", help="recorded in the output for provenance")
    ap.add_argument("--out", type=Path, default=REPO / "analysis")
    args = ap.parse_args()

    udb = args.udb_root.expanduser().resolve()
    pdir = udb / "spec/std/isa/param"
    if not pdir.is_dir():
        sys.exit(f"no spec/std/isa/param under {udb}")
    params = sorted(p.stem for p in pdir.glob("*.yaml"))

    model = read_tree(udb, MODEL_DIRS)
    cfgs = read_tree(udb, ["cfgs"])

    set_but_unread, unreferenced, used = [], [], []
    for name in params:
        pat = re.compile(r"\b" + re.escape(name) + r"\b")
        in_model = any(pat.search(t) for t in model.values())
        if in_model:
            used.append(name)
            continue
        if any(pat.search(t) for t in cfgs.values()):
            set_but_unread.append(name)
        else:
            unreferenced.append(name)

    total = len(params)
    print(f"revision            : {args.revision or '(unspecified)'}")
    print(f"parameters defined  : {total}")
    print(f"model files scanned : {len(model)}   config files: {len(cfgs)}")
    print()
    print(f"read by the ISA model        : {len(used):4}  ({100.0*len(used)/total:.1f}%)")
    print(f"set in cfgs/ but never read  : {len(set_but_unread):4}  ({100.0*len(set_but_unread)/total:.1f}%)")
    print(f"not referenced anywhere      : {len(unreferenced):4}  ({100.0*len(unreferenced)/total:.1f}%)")

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "orphan_params.json").write_text(json.dumps({
        "revision": args.revision,
        "counts": {
            "defined": total,
            "read_by_model": len(used),
            "set_but_unread": len(set_but_unread),
            "unreferenced": len(unreferenced),
        },
        "set_but_unread": set_but_unread,
        "unreferenced": unreferenced,
    }, indent=2))

    lines = [
        "# Parameters the ISA model does not read",
        "",
        f"Generated by `scripts/orphan_params.py` against `{args.revision or 'an unspecified revision'}`.",
        "",
        f"Of {total} parameters defined under `spec/std/isa/param/`, "
        f"{len(used)} are referenced by some file under `spec/std/isa/`. "
        f"The remaining {total - len(used)} are not.",
        "",
        "A parameter nothing reads cannot change observable architectural state:",
        "two configurations differing only in its value describe the same machine.",
        "That does not make every entry below a defect -- several appear to be",
        "defined ahead of the IDL intended to consume them -- but the distinction",
        "is mechanical, and it is not currently visible anywhere.",
        "",
        f"## Set in `cfgs/` but never read ({len(set_but_unread)})",
        "",
        "A configuration assigns these a value. Nothing in the model consults them,",
        "so the assignment has no modelled effect.",
        "",
    ]
    lines += [f"- `{n}`" for n in set_but_unread] or ["_none_"]
    lines += ["", f"## Not referenced anywhere ({len(unreferenced)})", ""]
    lines += [f"- `{n}`" for n in unreferenced] or ["_none_"]
    (args.out / "orphan_params.md").write_text("\n".join(lines) + "\n")

    print()
    print(f"wrote {args.out / 'orphan_params.json'}")
    print(f"wrote {args.out / 'orphan_params.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
